name: Build & Push Strapi Image to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: ap-south-1
      ECR_REPO: karunaissa-strapi   # your repo name
      ACCOUNT_ID: 301782007642      # org account ID

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          # We will add secrets later:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t strapi-app .

      - name: Tag image
        run: |
          IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:latest
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker tag strapi-app:latest $IMAGE_URI

      - name: Push image to ECR
        run: |
          docker push $IMAGE_URI

      - name: Output image tag
        id: image_tag
        run: echo "tag=${IMAGE_URI}" >> $GITHUB_OUTPUT